// Code generated by fyne-theme-generator

package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

type myThemeDark struct{}

func (myThemeDark) Color(c fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	switch c {
	case theme.ColorNameBackground:
		return color.NRGBA{R: 0x30, G: 0x30, B: 0x31, A: 0xff}
	case theme.ColorNameButton:
		return color.NRGBA{R: 0x4a, G: 0x4a, B: 0x4d, A: 0xff}
	case theme.ColorNameDisabledButton:
		return color.NRGBA{R: 0x28, G: 0x29, B: 0x2e, A: 0xff}
	case theme.ColorNameDisabled:
		return color.NRGBA{R: 0x69, G: 0x69, B: 0x6b, A: 0xff}
	case theme.ColorNameError:
		return color.NRGBA{R: 0xf4, G: 0x43, B: 0x36, A: 0xff}
	case theme.ColorNameFocus:
		return color.NRGBA{R: 0x16, G: 0x65, B: 0xcc, A: 0xf9}
	case theme.ColorNameForeground:
		return color.NRGBA{R: 0xf3, G: 0xf3, B: 0xf3, A: 0xff}
	case theme.ColorNameHover:
		return color.NRGBA{R: 0x75, G: 0x79, B: 0x76, A: 0x55}
	case theme.ColorNameInputBackground:
		return color.NRGBA{R: 0x1a, G: 0x1a, B: 0x1c, A: 0xff}
	case theme.ColorNamePlaceHolder:
		return color.NRGBA{R: 0xb2, G: 0xb2, B: 0xb2, A: 0xff}
	case theme.ColorNamePressed:
		return color.NRGBA{R: 0xff, G: 0xff, B: 0xff, A: 0x66}
	case theme.ColorNamePrimary:
		return color.NRGBA{R: 0x29, G: 0x6f, B: 0xf6, A: 0xff}
	case theme.ColorNameScrollBar:
		return color.NRGBA{R: 0xc0, G: 0xea, B: 0x43, A: 0x99}
	case theme.ColorNameShadow:
		return color.NRGBA{R: 0x60, G: 0x60, B: 0x60, A: 0x86}
	default:
		return theme.DefaultTheme().Color(c, v)
	}
}

func (myThemeDark) Font(s fyne.TextStyle) fyne.Resource {
	if s.Monospace {
		return theme.DefaultTheme().Font(s)
	}
	if s.Bold {
		if s.Italic {
			return theme.DefaultTheme().Font(s)
		}
		return theme.DefaultTheme().Font(s)
	}
	if s.Italic {
		return theme.DefaultTheme().Font(s)
	}
	return theme.DefaultTheme().Font(s)
}

func (myThemeDark) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}

func (myThemeDark) Size(s fyne.ThemeSizeName) float32 {
	switch s {
        case theme.SizeNameCaptionText:
                return 11
        case theme.SizeNameInlineIcon:
                return 20
        case theme.SizeNamePadding:
                return 3
        case theme.SizeNameScrollBar:
                return 12
        case theme.SizeNameScrollBarSmall:
                return 3
        case theme.SizeNameSeparatorThickness:
                return 1
        case theme.SizeNameText:
                return 14
        case theme.SizeNameInputBorder:
                return 1.2
	default:
		return theme.DefaultTheme().Size(s)
	}
}
