// Code generated by fyne-theme-generator

package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/theme"
)

type myThemeLight struct{}

func (myThemeLight) Color(c fyne.ThemeColorName, v fyne.ThemeVariant) color.Color {
	switch c {
	case theme.ColorNameBackground:
		return color.NRGBA{R: 0xdc, G: 0xd8, B: 0xd4, A: 0xff}
	case theme.ColorNameButton:
		return color.NRGBA{R: 0xca, G: 0xbc, B: 0xbb, A: 0xff}
	case theme.ColorNameDisabledButton:
		return color.NRGBA{R: 0xe5, G: 0xe3, B: 0xe3, A: 0xfb}
	case theme.ColorNameDisabled:
		return color.NRGBA{R: 0xb5, G: 0xb1, B: 0xb1, A: 0xff}
	case theme.ColorNameError:
		return color.NRGBA{R: 0xf4, G: 0x43, B: 0x36, A: 0xff}
	case theme.ColorNameFocus:
		return color.NRGBA{R: 0x50, G: 0xb5, B: 0xfa, A: 0x8c}
	case theme.ColorNameForeground:
		return color.NRGBA{R: 0xc, G: 0xc, B: 0xc, A: 0xff}
	case theme.ColorNameHover:
		return color.NRGBA{R: 0x91, G: 0xdd, B: 0x7a, A: 0xf9}
	case theme.ColorNameInputBackground:
		return color.NRGBA{R: 0xf3, G: 0xf3, B: 0xf3, A: 0xff}
	case theme.ColorNamePlaceHolder:
		return color.NRGBA{R: 0xa0, G: 0xb0, B: 0xf8, A: 0xff}
	case theme.ColorNamePressed:
		return color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x19}
	case theme.ColorNamePrimary:
		return color.NRGBA{R: 0x29, G: 0x6f, B: 0xf6, A: 0xff}
	case theme.ColorNameScrollBar:
		return color.NRGBA{R: 0x25, G: 0xab, B: 0x4, A: 0x99}
	case theme.ColorNameShadow:
		return color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x33}
	default:
		return theme.DefaultTheme().Color(c, v)
	}
}

func (myThemeLight) Font(s fyne.TextStyle) fyne.Resource {
	if s.Monospace {
		return theme.DefaultTheme().Font(s)
	}
	if s.Bold {
		if s.Italic {
			return theme.DefaultTheme().Font(s)
		}
		return theme.DefaultTheme().Font(s)
	}
	if s.Italic {
		return theme.DefaultTheme().Font(s)
	}
	return theme.DefaultTheme().Font(s)
}

func (myThemeLight) Icon(n fyne.ThemeIconName) fyne.Resource {
	return theme.DefaultTheme().Icon(n)
}

func (myThemeLight) Size(s fyne.ThemeSizeName) float32 {
	switch s {
	case theme.SizeNameCaptionText:
		return 11
	case theme.SizeNameInlineIcon:
		return 20
	case theme.SizeNamePadding:
		return 3
	case theme.SizeNameScrollBar:
		return 12
	case theme.SizeNameScrollBarSmall:
		return 3
	case theme.SizeNameSeparatorThickness:
		return 0.5
	case theme.SizeNameText:
		return 14
	case theme.SizeNameInputBorder:
		return 1.2
	default:
		return theme.DefaultTheme().Size(s)
	}
}
